services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - MPR_API_KEY=my-key

  frontend:
    build:
      context: ./frontend/app
      dockerfile: Dockerfile
    ports:
      - "3333:80"
    environment:
      - BACKEND_URL=backend:80
