services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

  frontend:
    build:
      context: ./frontend/app
      dockerfile: Dockerfile
    ports:
      - "3333:80"
    environment:
      - BACKEND_URL=backend:80
